Add color-canvas icon
telerik/kendo-icons pull request #24
Opened 2022-08-12 10:19 UTC by TeyaVes

2022-08-12 11:09 UTC, Juveniel approved these changes

2022-08-19 12:13 UTC, joneff requested changes
The icon exists as `droplet-slider`. Since we agreed that the name of the icons should represent what's on the icon and not what it is used for, `color-canvas` should be an alias.

Note: at some point in time all aliases should probably go, so using aliases is in no way sustainable.

2022-08-19 12:17 UTC, joneff requested changes
The commit [chore: add aliases for updated icon names](https://github.com/telerik/kendo-icons/pull/24/commits/6629c916e12f10824ffcfc7aa65d7a35d035fc83), should be a fix, since there is something for customers in it: aliases.

The commit should also list which aliases are added and for which icons. Something like

```bash
fix: add icon aliases

Added the following icon aliases:
* blockquote -> right-double-quotes
* report-header-section -> file-header
* report-footer-section -> file-footer
```

2022-09-01 15:19 UTC, joneff approved these changes

2022-09-01 15:19 UTC, merged