fix: add font-size to svg icons
telerik/kendo-icons pull request #57
Opened 2022-12-06 12:54 UTC by JoomFX

fixes https://github.com/telerik/kendo-themes/issues/4152

2022-12-06 12:58 UTC, TeyaVes requested changes
...

2022-12-06 12:59 UTC, TeyaVes approved these changes

2022-12-08 08:14 UTC, TeyaVes commented
I'll squash the commits after a review

2023-01-04 09:42 UTC, Juveniel approved these changes

2023-01-04 16:19 UTC, merged